Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "tomato juice")
Ingredient.create(name: "vodka")
Ingredient.create(name: "sea salt")
Ingredient.create(name: "milk")
Ingredient.create(name: "coffee liquor")
